### ISSUE TITLE
not found:  https://jitpack.io/adamko-dev/json5-kotlin/2.1.0/json5-kotlin-2.1.0.pom

### ISSUE THREAD

**Issue by nkbai** [adamko-dev/json5-kotlin#12]
it'a gradle build error.

```
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	dependencies {
		 implementation "adamko-dev:json5-kotlin:2.1.0"
	}
```

**Comment by aSemy** [comment]
Thanks for spotting that @nkbai, there's a mistake in the README. I've fixed it.

I had the wrong group ID because Jitpack changes the group ID. You can see the correct one here: https://jitpack.io/#adamko-dev/json5-kotlin/v2.1.0
